import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/theme/providers";
import { Navbar } from "@/components/landing/navbar";
import { ThemeController } from "@/components/theme/ThemeController";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Website Builder",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bolt.new - AI-Powered Website Builder',
  description: 'Create stunning websites in seconds with AI. Build, deploy, and iterate on full-stack web applications using natural language.',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased ${poppins.variable} font-poppins!`}
      >
        <Providers>
          <Navbar />
          <ThemeController />
          {children}
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              className: "bg-gradient-to-r! from-orange-500/70 to-pink-500/70 text-white border-orange-800!",
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
